### PR TITLE
Add shell completion

### PR DESCRIPTION
**Pull request by darklore**
Add installation of shell completion files to ytt homebrew Formula.

### CODE REVIEW

**Comment by DennisDenuto** [comment]
Thanks for the contribution @darklore 

If you can sign the CLA that would be much appreciated!

ytt folk reviewing this PR: assuming this gets merged in, a similar change would *eventually* need to be made upstream (to avoid this change being clobbered when ytt automates homebrew formula): https://github.com/vmware-tanzu/carvel-release-scripts/blob/main/scripts/homebrew_formula.yml

I've created an issue in carvel-release-scripts to help track this: https://github.com/vmware-tanzu/carvel-release-scripts/issues/3

**Comment by darklore** [comment]
Thank you review!
I signed the CLA.

**Comment by pivotaljohn** [comment]
@gcheadle-vmware — you've been up in this space; mind reviewing this PR?

**Review by gcheadle-vmware — APPROVED** [review]
These changes look good to me, I was able to test the installation out and found it working with zsh on macOS. I also found other brew formulas matching this pattern. 👍

**Pull request merged**
